
export const HIGHEST_QUALIFICATIONS = [
  "Below 10th",
  "10th Pass",
  "12th Pass",
  "ITI",
  "Diploma",
  "Certificate Course",
  "Undergraduate (Pursuing)",
  "Undergraduate (Completed)",
  "Postgraduate (Pursuing)",
  "Postgraduate (Completed)",
  "Doctorate (PhD)"
];

export const CLASS_YEAR_VALUES = [
  "1st Year", "2nd Year", "3rd Year", "4th Year", "5th Year",
  "Class 9", "Class 10", "Class 11", "Class 12",
  "Class 8", "Class 7", "Class 6", "Class 5",
  "Class 1", "Class 2", "Class 3", "Class 4",  
];

export const ALLOWED_LANGUAGES = [
  "hindi",
  "english",

  // major regional exam languages
  "assamese",
  "bengali",
  "gujarati",
  "kannada",
  "malayalam",
  "marathi",
  "odia",
  "punjabi",
  "tamil",
  "telugu",
  "urdu",

  // limited / specific exams
  "konkani",
  "manipuri",
  "nepali",
  "sindhi",
  "santhali",
  "kashmiri",
  "maithili",
  "dogri",
  "bodo",

  // classical / rare but officially used
  "sanskrit"
];


export const STATES = [
  // states
  "andhra pradesh",
  "arunachal pradesh",
  "assam",
  "bihar",
  "chhattisgarh",
  "goa",
  "gujarat",
  "haryana",
  "himachal pradesh",
  "jharkhand",
  "karnataka",
  "kerala",
  "madhya pradesh",
  "maharashtra",
  "manipur",
  "meghalaya",
  "mizoram",
  "nagaland",
  "odisha",
  "punjab",
  "rajasthan",
  "sikkim",
  "tamil nadu",
  "telangana",
  "tripura",
  "uttar pradesh",
  "uttarakhand",
  "west bengal",

  // union territories (treated as states)
  "andaman and nicobar islands",
  "chandigarh",
  "dadra and nagar haveli and daman and diu",
  "delhi",
  "jammu and kashmir",
  "ladakh",
  "lakshadweep",
  "puducherry"
];


export const DISTRICTS={
    "andhra pradesh": [
        "anakapalli",
        "anantapur",
        "annamayya",
        "bapatla",
        "chittoor",
        "dr. b.r. ambedkar konaseema",
        "east godavari",
        "eluru",
        "guntur",
        "kakinada",
        "krishna",
        "kurnool",
        "nandyal",
        "ntr",
        "palnadu",
        "parvathipuram manyam",
        "prakasam",
        "sri potti sriramulu nellore",
        "sri sathya sai",
        "srikakulam",
        "tirupati",
        "visakhapatnam",
        "vizianagaram",
        "west godavari",
        "ysr kadapa"
    ],
    "arunachal pradesh": [
        "anjaw",
        "changlang",
        "dibang valley",
        "east kameng",
        "east siang",
        "kamle",
        "kra daadi",
        "kurung kumey",
        "lepa rada",
        "lohit",
        "longding",
        "lower dibang valley",
        "lower siang",
        "lower subansiri",
        "namsai",
        "pakke kessang",
        "papum pare",
        "shi yomi",
        "siang",
        "tawang",
        "tirap",
        "upper siang",
        "upper subansiri",
        "west kameng",
        "west siang"
    ],
    "assam": [
        "baksa",
        "barpeta",
        "biswanath",
        "bongaigaon",
        "cachar",
        "charaideo",
        "chirang",
        "darrang",
        "dhemaji",
        "dhubri",
        "dibrugarh",
        "dima hasao",
        "goalpara",
        "golaghat",
        "hailakandi",
        "hojai",
        "jorhat",
        "kamrup",
        "kamrup metropolitan",
        "karbi anglong",
        "karimganj",
        "kokrajhar",
        "lakhimpur",
        "majuli",
        "morigaon",
        "nagaon",
        "nalbari",
        "sivasagar",
        "sonitpur",
        "south salmara-mankachar",
        "tinsukia",
        "udalguri",
        "west karbi anglong"
    ],
    "bihar": [
        "araria",
        "arwal",
        "aurangabad",
        "banka",
        "begusarai",
        "bhagalpur",
        "bhojpur",
        "buxar",
        "darbhanga",
        "east champaran",
        "gaya",
        "gopalganj",
        "jamui",
        "jehanabad",
        "kaimur",
        "katihar",
        "khagaria",
        "kishanganj",
        "lakhisarai",
        "madhepura",
        "madhubani",
        "munger",
        "muzaffarpur",
        "nalanda",
        "nawada",
        "patna",
        "purnia",
        "rohtas",
        "saharsa",
        "samastipur",
        "saran",
        "sheikhpura",
        "sheohar",
        "sitamarhi",
        "siwan",
        "supaul",
        "vaishali",
        "west champaran"
    ],
    "chhattisgarh": [
        "balod",
        "baloda bazar",
        "balrampur",
        "bastar",
        "bemetara",
        "bijapur",
        "bilaspur",
        "dantewada",
        "dhamtari",
        "durg",
        "gariaband",
        "gaurela-pendra-marwahi",
        "janjgir-champa",
        "jashpur",
        "kabirdham",
        "kanker",
        "kondagaon",
        "korba",
        "koriya",
        "mahasamund",
        "manendragarh-chirmiri-bharatpur",
        "mohla-manpur-ambagarh chowki",
        "mungeli",
        "narayanpur",
        "raigarh",
        "raipur",
        "rajnandgaon",
        "sarangarh-bilaigarh",
        "shakti",
        "sukma",
        "surajpur",
        "surguja"
    ],
    "goa": [
        "north goa",
        "south goa"
    ],
    "gujarat": [
        "ahmedabad",
        "amreli",
        "anand",
        "aravalli",
        "banaskantha",
        "bharuch",
        "bhavnagar",
        "botad",
        "chhota udaipur",
        "dahod",
        "dang",
        "devbhoomi dwarka",
        "gandhinagar",
        "gir somnath",
        "jamnagar",
        "junagadh",
        "kheda",
        "kutch",
        "mahisagar",
        "mehsana",
        "morbi",
        "narmada",
        "navsari",
        "panchmahal",
        "patan",
        "porbandar",
        "rajkot",
        "sabarkantha",
        "surat",
        "surendranagar",
        "tapi",
        "vadodara",
        "valsad"
    ],
    "haryana": [
        "ambala",
        "bhiwani",
        "charkhi dadri",
        "faridabad",
        "fatehabad",
        "gurugram",
        "hisar",
        "jhajjar",
        "jind",
        "kaithal",
        "karnal",
        "kurukshetra",
        "mahendragarh",
        "nuh",
        "palwal",
        "panchkula",
        "panipat",
        "rewari",
        "rohtak",
        "sirsa",
        "sonipat",
        "yamunanagar"
    ],
    "himachal pradesh": [
        "bilaspur",
        "chamba",
        "hamirpur",
        "kangra",
        "kinnaur",
        "kullu",
        "lahaul and spiti",
        "mandi",
        "shimla",
        "sirmaur",
        "solan",
        "una"
    ],
    "jharkhand": [
        "bokaro",
        "chatra",
        "deoghar",
        "dhanbad",
        "dumka",
        "east singhbhum",
        "garhwa",
        "giridih",
        "godda",
        "gumla",
        "hazaribagh",
        "jamtara",
        "khunti",
        "koderma",
        "latehar",
        "lohardaga",
        "pakur",
        "palamu",
        "ramgarh",
        "ranchi",
        "sahebganj",
        "seraikela kharsawan",
        "simdega",
        "west singhbhum"
    ],
    "karnataka": [
        "bagalkot",
        "ballari",
        "belagavi",
        "bengaluru rural",
        "bengaluru urban",
        "bidar",
        "chamarajanagar",
        "chikkaballapur",
        "chikkamagaluru",
        "chitradurga",
        "dakshina kannada",
        "davanagere",
        "dharwad",
        "gadag",
        "hassan",
        "haveri",
        "kalaburagi",
        "kodagu",
        "kolar",
        "koppal",
        "mandya",
        "mysuru",
        "raichur",
        "ramanagara",
        "shivamogga",
        "tumakuru",
        "udupi",
        "uttara kannada",
        "vijayanagara",
        "vijayapura",
        "yadgir"
    ],
    "kerala": [
        "alappuzha",
        "ernakulam",
        "idukki",
        "kannur",
        "kasaragod",
        "kollam",
        "kottayam",
        "kozhikode",
        "malappuram",
        "palakkad",
        "pathanamthitta",
        "thiruvananthapuram",
        "thrissur",
        "wayanad"
    ],
    "madhya pradesh": [
        "agar malwa",
        "alirajpur",
        "anuppur",
        "ashoknagar",
        "balaghat",
        "barwani",
        "betul",
        "bhind",
        "bhopal",
        "burhanpur",
        "chhatarpur",
        "chhindwara",
        "damoh",
        "datia",
        "dewas",
        "dhar",
        "dindori",
        "guna",
        "gwalior",
        "harda",
        "hoshangabad",
        "indore",
        "jabalpur",
        "jhabua",
        "katni",
        "khandwa",
        "khargone",
        "maihar",
        "mandla",
        "mandsaur",
        "morena",
        "narmadapuram",
        "narsinghpur",
        "neemuch",
        "niwari",
        "panna",
        "raisen",
        "rajgarh",
        "ratlam",
        "rewa",
        "sagar",
        "satna",
        "sehore",
        "seoni",
        "shahdol",
        "shajapur",
        "sheopur",
        "shivpuri",
        "sidhi",
        "singrauli",
        "tikamgarh",
        "ujjain",
        "umaria",
        "vidisha"
    ],
    "maharashtra": [
        "ahilyanagar",
        "akola",
        "amravati",
        "beed",
        "bhandara",
        "buldhana",
        "chandrapur",
        "chhatrapati sambhajinagar",
        "dharashiv",
        "dhule",
        "gadchiroli",
        "gondia",
        "hingoli",
        "jalgaon",
        "jalna",
        "kolhapur",
        "latur",
        "mumbai city",
        "mumbai suburban",
        "nagpur",
        "nanded",
        "nandurbar",
        "nashik",
        "palghar",
        "parbhani",
        "pune",
        "raigad",
        "ratnagiri",
        "sangli",
        "satara",
        "sindhudurg",
        "solapur",
        "thane",
        "wardha",
        "washim",
        "yavatmal"
    ],
    "manipur": [
        "bishnupur",
        "chandel",
        "churachandpur",
        "imphal east",
        "imphal west",
        "jiribam",
        "kakching",
        "kamjong",
        "kangpokpi",
        "noney",
        "pherzawl",
        "senapati",
        "tamenglong",
        "tengnoupal",
        "thoubal",
        "ukhrul"
    ],
    "meghalaya": [
        "east garo hills",
        "east jaintia hills",
        "east khasi hills",
        "north garo hills",
        "ri-bhoi",
        "south garo hills",
        "south west garo hills",
        "south west khasi hills",
        "west garo hills",
        "west jaintia hills",
        "west khasi hills"
    ],
    "mizoram": [
        "aizawl",
        "champhai",
        "hnahthial",
        "khawzawl",
        "kolasib",
        "lawngtlai",
        "lunglei",
        "mamit",
        "saiha",
        "saitual",
        "serchhip"
    ],
    "nagaland": [
        "ch\u00fcmoukedima",
        "dimapur",
        "kiphire",
        "kohima",
        "longleng",
        "mokokchung",
        "mon",
        "niuland",
        "noklak",
        "peren",
        "phek",
        "shamator",
        "tseminy\u00fc",
        "tuensang",
        "wokha",
        "z\u00fcnheboto"
    ],
    "sikkim": [
        "east sikkim",
        "north sikkim",
        "pakyong",
        "soreng",
        "south sikkim",
        "west sikkim"
    ],
    "tripura": [
        "dhalai",
        "gomati",
        "khowai",
        "north tripura",
        "sepahijala",
        "south tripura",
        "unakoti",
        "west tripura"
    ],
    "odisha": [
        "angul",
        "balangir",
        "balasore",
        "bargarh",
        "bhadrak",
        "boudh",
        "cuttack",
        "deogarh",
        "dhenkanal",
        "gajapati",
        "ganjam",
        "jagatsinghpur",
        "jajpur",
        "jharsuguda",
        "kalahandi",
        "kandhamal",
        "kendrapara",
        "kendujhar",
        "khordha",
        "koraput",
        "malkangiri",
        "mayurbhanj",
        "nabarangpur",
        "nayagarh",
        "nuapada",
        "puri",
        "rayagada",
        "sambalpur",
        "subarnapur",
        "sundargarh"
    ],
    "punjab": [
        "amritsar",
        "barnala",
        "bathinda",
        "faridkot",
        "fatehgarh sahib",
        "fazilka",
        "ferozepur",
        "gurdaspur",
        "hoshiarpur",
        "jalandhar",
        "kapurthala",
        "ludhiana",
        "malerkotla",
        "mansa",
        "moga",
        "pathankot",
        "patiala",
        "rupnagar",
        "sahibzada ajit singh nagar",
        "sangrur",
        "shahid bhagat singh nagar",
        "sri muktsar sahib",
        "tarn taran"
    ],
    "rajasthan": [
        "ajmer",
        "alwar",
        "anupgarh",
        "balotra",
        "banswara",
        "baran",
        "barmer",
        "beawar",
        "bharatpur",
        "bhilwara",
        "bikaner",
        "bundi",
        "chittorgarh",
        "churu",
        "dausa",
        "deeg",
        "dholpur",
        "didwana-kuchaman",
        "dudu",
        "dungarpur",
        "gangapur city",
        "hanumangarh",
        "jaipur north",
        "jaipur south",
        "jaisalmer",
        "jalore",
        "jhalawar",
        "jhunjhunu",
        "jodhpur east",
        "jodhpur west",
        "karauli",
        "kekri",
        "khairthal-tijara",
        "kota",
        "kotputli-behror",
        "nagaur",
        "neem ka thana",
        "pali",
        "phalodi",
        "pratapgarh",
        "rajsamand",
        "salumbar",
        "sanchore",
        "sawai madhopur",
        "shahpura",
        "sikar",
        "sirohi",
        "sri ganganagar",
        "tonk",
        "udaipur"
    ],
    "tamil nadu": [
        "ariyalur",
        "chengalpattu",
        "chennai",
        "coimbatore",
        "cuddalore",
        "dharmapuri",
        "dindigul",
        "erode",
        "kallakurichi",
        "kanchipuram",
        "kanyakumari",
        "karur",
        "krishnagiri",
        "madurai",
        "mayiladuthurai",
        "nagapattinam",
        "namakkal",
        "nilgiris",
        "perambalur",
        "pudukkottai",
        "ramanathapuram",
        "ranipet",
        "salem",
        "sivaganga",
        "tenkasi",
        "thanjavur",
        "theni",
        "thoothukudi",
        "tiruchirappalli",
        "tirunelveli",
        "tirupattur",
        "tiruppur",
        "tiruvallur",
        "tiruvannamalai",
        "tiruvarur",
        "vellore",
        "viluppuram",
        "virudhunagar"
    ],
    "telangana": [
        "adilabad",
        "bhadradri kothagudem",
        "hanumakonda",
        "hyderabad",
        "jagtial",
        "jangaon",
        "jayashankar bhupalpally",
        "jogulamba gadwal",
        "kamareddy",
        "karimnagar",
        "khammam",
        "komaram bheem",
        "mahabubabad",
        "mahabubnagar",
        "mancherial",
        "medak",
        "medchal-malkajgiri",
        "mulugu",
        "nagarkurnool",
        "nalgonda",
        "narayanpet",
        "nirmal",
        "nizamabad",
        "peddapalli",
        "rajanna sircilla",
        "ranga reddy",
        "sangareddy",
        "siddipet",
        "suryapet",
        "vikarabad",
        "wanaparthy",
        "warangal",
        "yadadri bhuvanagiri"
    ],
    "uttar pradesh": [
        "agra",
        "aligarh",
        "ambedkar nagar",
        "amethi",
        "amroha",
        "auraiya",
        "ayodhya",
        "azamgarh",
        "baghpat",
        "bahraich",
        "ballia",
        "balrampur",
        "banda",
        "barabanki",
        "bareilly",
        "basti",
        "bhadohi",
        "bijnor",
        "budaun",
        "bulandshahr",
        "chandauli",
        "chitrakoot",
        "deoria",
        "etah",
        "etawah",
        "farrukhabad",
        "fatehpur",
        "firozabad",
        "gautam buddha nagar",
        "ghaziabad",
        "ghazipur",
        "gonda",
        "gorakhpur",
        "hamirpur",
        "hapur",
        "hardoi",
        "hathras",
        "jalaun",
        "jaunpur",
        "jhansi",
        "kannauj",
        "kanpur dehat",
        "kanpur nagar",
        "kasganj",
        "kaushambi",
        "kushinagar",
        "lakhimpur kheri",
        "lalitpur",
        "lucknow",
        "maharajganj",
        "mahoba",
        "mainpuri",
        "mathura",
        "mau",
        "meerut",
        "mirzapur",
        "moradabad",
        "muzaffarnagar",
        "pilibhit",
        "pratapgarh",
        "prayagraj",
        "raebareli",
        "rampur",
        "saharanpur",
        "sambhal",
        "sant kabir nagar",
        "shahjahanpur",
        "shamli",
        "shravasti",
        "siddharthnagar",
        "sitapur",
        "sonbhadra",
        "sultanpur",
        "unnao",
        "varanasi"
    ],
    "uttarakhand": [
        "almora",
        "bageshwar",
        "chamoli",
        "champawat",
        "dehradun",
        "haridwar",
        "nainital",
        "pauri garhwal",
        "pithoragarh",
        "rudraprayag",
        "tehri garhwal",
        "udham singh nagar",
        "uttarkashi"
    ],
    "west bengal": [
        "alipurduar",
        "bankura",
        "birbhum",
        "cooch behar",
        "dakshin dinajpur",
        "darjeeling",
        "hooghly",
        "howrah",
        "jalpaiguri",
        "jhargram",
        "kalimpong",
        "kolkata",
        "malda",
        "murshidabad",
        "nadia",
        "north 24 parganas",
        "paschim bardhaman",
        "paschim medinipur",
        "purba bardhaman",
        "purba medinipur",
        "purulia",
        "south 24 parganas",
        "uttar dinajpur"
    ],
    "andaman and nicobar islands": [
        "nicobar",
        "north and middle andaman",
        "south andaman"
    ],
    "chandigarh": [
        "chandigarh"
    ],
    "dadra and nagar haveli and daman and diu": [
        "daman",
        "diu",
        "dadra and nagar haveli"
    ],
    "delhi": [
        "central delhi",
        "east delhi",
        "new delhi",
        "north delhi",
        "north east delhi",
        "north west delhi",
        "shahdara",
        "south delhi",
        "south east delhi",
        "south west delhi",
        "west delhi"
    ],
    "jammu and kashmir": [
        "anantnag",
        "bandipora",
        "baramulla",
        "budgam",
        "doda",
        "ganderbal",
        "jammu",
        "kathua",
        "kishtwar",
        "kulgam",
        "kupwara",
        "poonch",
        "pulwama",
        "rajouri",
        "ramban",
        "reasi",
        "samba",
        "shopian",
        "srinagar",
        "udhampur"
    ],
    "ladakh": [
        "kargil",
        "leh"
    ],
    "lakshadweep": [
        "lakshadweep"
    ],
    "puducherry": [
        "karaikal",
        "mahe",
        "puducherry",
        "yanam"
    ]
}
